name: NewAvica

on:
  workflow_dispatch:

jobs:
  build:
    name: Instance 1
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Downloading & Installing Essentials
        run: |
          echo "Running Instance 1"
          Invoke-WebRequest -Uri "https://gitlab.com/gusta7w7/pcrdp-avica/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
